// tb_scan_atpg.sv
// ---------------------------------------------------------------------------
// Verifies the full-scan flow on rtl/scan_demo.sv in two stages:
//
//   Phase A -- ATPG replay.  Reads the test patterns generated by
//   scripts/atpg.py (sim/scan_vectors.vec), and for each pattern runs the
//   real scan protocol against the DUT: shift the pattern in (scan_en=1),
//   capture one functional clock (scan_en=0), shift the response out
//   (scan_en=1), and check the captured value bit-for-bit. This closes the
//   same loop the JTAG Tcl generator + replay does: bits a separate tool
//   computed are run against the RTL.
//
//   Phase B -- hardware mutation.  Proves the ATPG verdicts in silicon-like
//   form by forcing single stuck-at faults onto the combinational cloud at
//   run time (the hardware analogue of the SVA mutation testing in this repo):
//     * a DETECTABLE fault (n0 stuck-at-0) must change the captured response
//       for at least one pattern -- i.e. ATPG can catch it;
//     * the REDUNDANT fault the tool found (ginv1 stuck-at-1) must leave the
//       captured response unchanged for EVERY pattern -- a hardware proof that
//       no test can distinguish it, exactly as ATPG reported.
//
// $fatal (non-zero exit) on any failure; prints "RESULT : PASS" so the CI
// log-gate accepts it like the other benches.

`timescale 1ns/1ps
module tb_scan_atpg;

  localparam int N = 4;

  logic         clk = 1'b0;
  logic         rst_n;
  logic         scan_en;
  logic         scan_in;
  logic         scan_out;
  logic         fault_en;
  logic [3:0]   fault_site;
  logic         fault_val;
  logic [N-1:0] q;

  scan_demo #(.N(N)) dut (
    .clk(clk), .rst_n(rst_n),
    .scan_en(scan_en), .scan_in(scan_in), .scan_out(scan_out),
    .fault_en(fault_en), .fault_site(fault_site), .fault_val(fault_val),
    .q(q)
  );

  int errors = 0;
  int checks = 0;

  // one TCK: signals must be set by the caller first
  task automatic pulse();
    #2 clk = 1'b1;
    #2 clk = 1'b0;
    #2;
  endtask

  // Run the full scan protocol for one pattern under a given fault config and
  // return the captured response. load/cap are q[3:0] values.
  task automatic run_pattern(input  logic [N-1:0] load,
                             input  logic         fen,
                             input  logic [3:0]   fsite,
                             input  logic         fval,
                             output logic [N-1:0] cap);
    fault_en = fen; fault_site = fsite; fault_val = fval;

    // shift the pattern in: feed q[N-1] first so it lands in the tail flop
    scan_en = 1'b1;
    for (int k = N-1; k >= 0; k--) begin
      scan_in = load[k];
      pulse();
    end

    // capture one functional clock
    scan_en = 1'b0;
    pulse();

    // shift the captured value out: scan_out gives q[N-1] first (MSB)
    scan_en = 1'b1;
    scan_in = 1'b0;
    for (int k = N-1; k >= 0; k--) begin
      cap[k] = scan_out;
      pulse();
    end

    fault_en = 1'b0;
  endtask

  // file-parsing scratch
  integer        fd, code, nf;
  reg [8*256-1:0] line;
  integer        l3, l2, l1, l0, e3, e2, e1, e0;
  logic [N-1:0]  load_v, exp_v, got_v;
  int            pat;

  initial begin
    $dumpfile("sim/scan_atpg.vcd");
    $dumpvars(0, tb_scan_atpg);

    scan_en = 0; scan_in = 0; fault_en = 0; fault_site = 0; fault_val = 0;

    // async reset pulse (clean under 2- and 4-state simulators)
    rst_n = 1'b1; #2;
    rst_n = 1'b0; #5;
    rst_n = 1'b1; #5;

    // ---- Phase A: replay the ATPG patterns against the good machine ----
    $display("-- Phase A: ATPG pattern replay (good machine) --");
    fd = $fopen("sim/scan_vectors.vec", "r");
    if (fd == 0)
      $fatal(1, "cannot open sim/scan_vectors.vec (run scripts/atpg.py first)");

    pat = 0;
    while (!$feof(fd)) begin
      code = $fgets(line, fd);
      nf = (code != 0) ?
           $sscanf(line, "%d %d %d %d %d %d %d %d",
                   l3, l2, l1, l0, e3, e2, e1, e0) : 0;
      if (nf == 8) begin                       // a data line (comments give <8)
        load_v = {l3[0], l2[0], l1[0], l0[0]}; // q3 q2 q1 q0
        exp_v  = {e3[0], e2[0], e1[0], e0[0]}; // n3 n2 n1 n0
        run_pattern(load_v, 1'b0, 4'd0, 1'b0, got_v);
        checks++;
        if (got_v !== exp_v) begin
          errors++;
          $display("  [FAIL] pattern %0d load=0x%0h: captured 0x%0h expected 0x%0h",
                   pat, load_v, got_v, exp_v);
        end else begin
          $display("  [ ok ] pattern %0d load=0x%0h -> capture 0x%0h",
                   pat, load_v, got_v);
        end
        pat++;
      end
    end
    $fclose(fd);
    if (pat == 0) begin
      errors++;
      $display("  [FAIL] no patterns read from vector file");
    end

    // ---- Phase B: hardware mutation -- prove the ATPG verdicts ----
    $display("\n-- Phase B: hardware mutation (fault injection) --");
    begin
      logic [N-1:0] gold, bad;
      int  diffs;

      // (1) DETECTABLE: n0 stuck-at-0 (site 1) must differ on >=1 pattern.
      diffs = 0;
      for (int v = 0; v < (1<<N); v++) begin
        run_pattern(v[N-1:0], 1'b0, 4'd0, 1'b0, gold);   // good
        run_pattern(v[N-1:0], 1'b1, 4'd1, 1'b0, bad);    // n0 SA0
        if (bad !== gold) diffs++;
      end
      checks++;
      if (diffs > 0)
        $display("  [ ok ] detectable fault n0/SA0: response differs on %0d/%0d patterns",
                 diffs, (1<<N));
      else begin
        errors++;
        $display("  [FAIL] n0/SA0 produced no observable difference (should be testable)");
      end

      // (2) REDUNDANT: ginv1 stuck-at-1 (site 2) must NEVER differ.
      diffs = 0;
      for (int v = 0; v < (1<<N); v++) begin
        run_pattern(v[N-1:0], 1'b0, 4'd0, 1'b0, gold);   // good
        run_pattern(v[N-1:0], 1'b1, 4'd2, 1'b1, bad);    // ginv1 SA1
        if (bad !== gold) diffs++;
      end
      checks++;
      if (diffs == 0)
        $display("  [ ok ] redundant fault ginv1/SA1: no pattern distinguishes it (untestable, as ATPG found)");
      else begin
        errors++;
        $display("  [FAIL] ginv1/SA1 was observable on %0d patterns (ATPG called it redundant)",
                 diffs);
      end
    end

    // ---- summary ----
    $display("\n================ SCAN/ATPG SUMMARY ================");
    $display("checks run : %0d", checks);
    $display("errors     : %0d", errors);
    if (errors == 0) $display("RESULT     : PASS");
    else             $display("RESULT     : FAIL");
    $display("===================================================");

    if (errors != 0)
      $fatal(1, "scan/ATPG verification FAILED with %0d error(s)", errors);
    $finish;
  end

  // safety net so a hang can't masquerade as a pass
  initial begin
    #200000;
    $fatal(1, "TIMEOUT: scan/ATPG testbench did not finish");
  end

endmodule